# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: CGO_ENABLED=0 go build -o goDumper-x64 goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-x64
        path: ./goDumper-x64

    - name: Build
      run: CGO_ENABLED=0 GOARCH=mips GOOS=linux go build -o goDumper-mips goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-mips
        path: ./goDumper-mips

    - name: Build
      run: CGO_ENABLED=0 GOARCH=mipsle GOOS=linux go build -o goDumper-mipsle goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-mipsle
        path: ./goDumper-mipsle

    - name: Build
      run: CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -o goDumper-arm64 goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-arm64
        path: ./goDumper-arm64

    - name: Build
      run: CGO_ENABLED=0 GOARCH=arm GOOS=linux go build -o goDumper-arm goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-arm
        path: ./goDumper-arm

    - name: Build
      run: CGO_ENABLED=0 GOARCH=386 GOOS=linux go build -o goDumper-386 goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-386
        path: ./goDumper-386

    - name: Build
      run: CGO_ENABLED=0 GOARCH=ppc64le GOOS=linux go build -o goDumper-ppc64le goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-ppc64le
        path: ./goDumper-ppc64le

    - name: Build
      run: CGO_ENABLED=0 GOARCH=ppc64 GOOS=linux go build -o goDumper-ppc64 goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-ppc64
        path: ./goDumper-ppc64

    - name: Build
      run: CGO_ENABLED=0 GOARCH=mips64le GOOS=linux go build -o goDumper-mips64le goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-mips64le
        path: ./goDumper-mips64le

    - name: Build
      run: CGO_ENABLED=0 GOARCH=mips64 GOOS=linux go build -o goDumper-mips64 goDumper.go 
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: goDumper-mips64
        path: ./goDumper-mips64
